package com.bosams.learnerparent.domain;

import com.bosams.learnerparent.dto.LearnerParentDtos.*;
import jakarta.validation.Valid;
import java.time.LocalDate;
import java.util.Map;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/v1")
public class LearnerParentController {
    private final LearnerParentService s;
    public LearnerParentController(LearnerParentService s){this.s=s;}

    @PostMapping("/admissions/applications") Object createApplication(@RequestBody @Valid ApplicationRequest r){return s.createApplication(r);}    
    @GetMapping("/admissions/applications/{id}") Object getApplication(@PathVariable Long id){return s.getApplication(id);}    
    @GetMapping("/admissions/applications") Page<?> listApplications(@RequestParam Long schoolId,@RequestParam(required=false) String status,@RequestParam(required=false) @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate from,@RequestParam(required=false) @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate to, Pageable p){return s.listApplications(schoolId,status,from,to,p);}    
    @PostMapping("/admissions/applications/{id}/approve") Object approve(@PathVariable Long id,@RequestBody(required=false) DecisionRequest r){return s.decideApplication(id,"APPROVED",r==null?new DecisionRequest(null,null):r);}    
    @PostMapping("/admissions/applications/{id}/reject") Object reject(@PathVariable Long id,@RequestBody(required=false) DecisionRequest r){return s.decideApplication(id,"REJECTED",r==null?new DecisionRequest(null,null):r);}    
    @PostMapping("/admissions/applications/{id}/waitlist") Object wait(@PathVariable Long id,@RequestBody(required=false) DecisionRequest r){return s.decideApplication(id,"WAITLISTED",r==null?new DecisionRequest(null,null):r);}    

    @PostMapping("/learners") Object createLearner(@RequestBody @Valid LearnerRequest r){return s.createLearner(r);} @GetMapping("/learners/{id}") Object getLearner(@PathVariable Long id){return s.getLearner(id);} @GetMapping("/learners") Page<?> listLearners(@RequestParam Long schoolId,@RequestParam(required=false) String status,@RequestParam(required=false) Long academicYearId,@RequestParam(required=false) Long gradeId,@RequestParam(required=false) Long classRoomId,Pageable p){return s.listLearners(schoolId,status,academicYearId,gradeId,classRoomId,p);} @PutMapping("/learners/{id}") Object updateLearner(@PathVariable Long id,@RequestBody @Valid LearnerRequest r){return s.updateLearner(id,r);} @PostMapping("/learners/{id}/archive") Object archiveLearner(@PathVariable Long id,@RequestBody @Valid ArchiveRequest r){return s.archiveLearner(id,r);} @PostMapping("/learners/{id}/restore") Object restoreLearner(@PathVariable Long id){return s.restoreLearner(id);} @PostMapping("/learners/{id}/transfer") Object transferLearner(@PathVariable Long id,@RequestBody @Valid LearnerTransferRequest r){return s.transferLearner(id,r);}    

    @PostMapping("/parents") Object createParent(@RequestBody @Valid ParentRequest r){return s.createParent(r);} @GetMapping("/parents/{id}") Object getParent(@PathVariable Long id){return s.getParent(id);} @GetMapping("/parents") Page<?> listParents(@RequestParam Long schoolId,@RequestParam(required=false) String status,Pageable p){return s.listParents(schoolId,status,p);} @PutMapping("/parents/{id}") Object updateParent(@PathVariable Long id,@RequestBody @Valid ParentRequest r){return s.updateParent(id,r);} @PostMapping("/parents/{id}/archive") Object archiveParent(@PathVariable Long id,@RequestBody @Valid ArchiveRequest r){return s.archiveParent(id,r);} @PostMapping("/parents/{id}/restore") Object restoreParent(@PathVariable Long id){return s.restoreParent(id);}    
    @PostMapping("/learners/{learnerId}/parents/link") Object linkParent(@PathVariable Long learnerId,@RequestBody @Valid LinkParentRequest r){return s.linkParent(learnerId,r);} @DeleteMapping("/learners/{learnerId}/parents/{parentId}/unlink") void unlinkParent(@PathVariable Long learnerId,@PathVariable Long parentId,@RequestParam Long schoolId){s.unlinkParent(learnerId,parentId,schoolId);} @GetMapping("/learners/{learnerId}/parents") Page<?> learnerParents(@PathVariable Long learnerId,@RequestParam Long schoolId,Pageable p){return s.learnerParents(schoolId,learnerId,p);} @GetMapping("/parents/{parentId}/learners") Page<?> parentLearners(@PathVariable Long parentId,@RequestParam Long schoolId,Pageable p){return s.parentLearners(schoolId,parentId,p);} @GetMapping("/reports/parents/primary-contacts") Page<?> primaryContacts(@RequestParam Long schoolId,Pageable p){return s.primaryContacts(schoolId,p);}    

    @PostMapping("/learners/{learnerId}/activities") Object addActivity(@PathVariable Long learnerId,@RequestBody @Valid ActivityRequest r){return s.addActivity(learnerId,r);} @GetMapping("/learners/{learnerId}/activities") Page<?> listActivities(@PathVariable Long learnerId,@RequestParam Long schoolId,Pageable p){return s.listActivities(schoolId,learnerId,p);} @DeleteMapping("/learners/{learnerId}/activities/{id}") void delActivity(@PathVariable Long id){s.deleteActivity(id);}    
    @PostMapping("/learners/{learnerId}/transport") Object addTransport(@PathVariable Long learnerId,@RequestBody @Valid TransportRequest r){return s.addTransport(learnerId,r);} @GetMapping("/learners/{learnerId}/transport") Page<?> listTransport(@PathVariable Long learnerId,@RequestParam Long schoolId,Pageable p){return s.listTransport(schoolId,learnerId,p);} @DeleteMapping("/learners/{learnerId}/transport/{id}") void delTransport(@PathVariable Long id){s.deleteTransport(id);}    
    @PostMapping("/learners/{learnerId}/leadership") Object addLeadership(@PathVariable Long learnerId,@RequestBody @Valid LeadershipRequest r){return s.addLeadership(learnerId,r);} @GetMapping("/learners/{learnerId}/leadership") Page<?> listLeadership(@PathVariable Long learnerId,@RequestParam Long schoolId,Pageable p){return s.listLeadership(schoolId,learnerId,p);} @GetMapping("/reports/leadership/rcl") Page<?> rcl(@RequestParam Long schoolId,@RequestParam Long academicYearId,Pageable p){return s.listRcl(schoolId,academicYearId,p);}    
    @PostMapping("/learners/{learnerId}/incidents") Object addIncident(@PathVariable Long learnerId,@RequestBody @Valid IncidentRequest r){return s.addIncident(learnerId,r);} @GetMapping("/learners/{learnerId}/incidents") Page<?> listIncidents(@PathVariable Long learnerId,@RequestParam Long schoolId,Pageable p){return s.listIncidents(schoolId,learnerId,p);}    
    @PostMapping("/learners/{learnerId}/barriers") Object addBarrier(@PathVariable Long learnerId,@RequestBody @Valid BarrierRequest r){return s.addBarrier(learnerId,r);} @GetMapping("/learners/{learnerId}/barriers") Page<?> listBarriers(@PathVariable Long learnerId,@RequestParam Long schoolId,Pageable p){return s.listBarriers(schoolId,learnerId,p);}    
    @PostMapping("/learners/{learnerId}/mentor") Object addMentor(@PathVariable Long learnerId,@RequestBody @Valid MentorRequest r){return s.addMentor(learnerId,r);} @GetMapping("/learners/{learnerId}/mentor") Page<?> listMentor(@PathVariable Long learnerId,@RequestParam Long schoolId,Pageable p){return s.listMentors(schoolId,learnerId,p);}    
    @PostMapping("/learners/{learnerId}/discipline") Object addDiscipline(@PathVariable Long learnerId,@RequestBody @Valid DisciplineRequest r){return s.addDiscipline(learnerId,r);} @GetMapping("/learners/{learnerId}/discipline") Page<?> listDiscipline(@PathVariable Long learnerId,@RequestParam Long schoolId,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate from,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate to,Pageable p){return s.listDiscipline(schoolId,learnerId,from,to,p);} @PostMapping("/learners/{learnerId}/detentions") Object addDetention(@PathVariable Long learnerId,@RequestBody @Valid DetentionRequest r){return s.addDetention(learnerId,r);} @GetMapping("/learners/{learnerId}/detentions") Page<?> listDetentions(@PathVariable Long learnerId,@RequestParam Long schoolId,Pageable p){return s.listDetentions(schoolId,learnerId,p);}    
    @GetMapping("/reports/discipline/summary") Map<String,Object> disciplineSummary(@RequestParam Long schoolId,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate from,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate to){return s.disciplineSummary(schoolId,from,to);}    
    @PostMapping("/attendance/learners") Object attendance(@RequestBody @Valid AttendanceCaptureRequest r){return s.captureAttendance(r);} @GetMapping("/attendance/learners") Page<?> attendanceList(@RequestParam Long schoolId,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate date,@RequestParam(required=false) Long classRoomId,@RequestParam(required=false) Integer period,Pageable p){return s.attendanceByClass(schoolId,date,classRoomId,period,p);} @GetMapping("/attendance/learners/{learnerId}") Page<?> learnerAttendance(@PathVariable Long learnerId,@RequestParam Long schoolId,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate from,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate to,Pageable p){return s.learnerAttendance(schoolId,learnerId,from,to,p);} @PostMapping("/attendance/learners/{learnerId}/notify-absence") Object notify(@PathVariable Long learnerId,@RequestBody @Valid AbsenceNotifyRequest r){return s.notifyAbsence(learnerId,r);} @GetMapping("/reports/attendance/summary") Map<String,Object> attendanceSummary(@RequestParam Long schoolId,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate from,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate to){return s.attendanceSummary(schoolId,from,to);}    

    @GetMapping("/reports/enrolment") Map<String,Object> enrol(@RequestParam Long schoolId,@RequestParam Long academicYearId){return s.enrolment(schoolId,academicYearId);} @GetMapping("/reports/learners/age-list") Object ageList(@RequestParam Long schoolId,@RequestParam Long academicYearId,@RequestParam Long gradeId,@RequestParam(required=false) @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate referenceDate){return s.ageList(schoolId,academicYearId,gradeId,referenceDate==null?LocalDate.now():referenceDate);} @GetMapping("/reports/activities/members") Page<?> activityMembers(@RequestParam Long schoolId,@RequestParam String activityType,@RequestParam Long activityId,Pageable p){return s.activityMembers(schoolId,activityType,activityId,p);} @GetMapping("/reports/learners/aggregate") Object aggregate(@RequestParam Long schoolId,@RequestParam Long academicYearId){return s.aggregateLearners(schoolId,academicYearId);}    
}
